development:
  app_id: xxx
  secret: xxx
  api_key: xxx
  callback_url: xxx


staging:
  app_id: xxx
  secret: xxx
  api_key: xxx
  callback_url: xxx

production:
  app_id: xxx
  secret: xxx
  api_key: xxx
  callback_url: xxx

test:
  app_id: xxx
  secret: xxx
  api_key: xxx
  callback_url: xxx

drm:
  app_id: xxx
  secret: xxx
  api_key: xxx
  callback_url: xxx
